### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by NigelReburn** [jugla/worldtidesinfocustom#10] opened 2021-05-29 12:44 UTC
Hi, this will no longer load as an integration as neither standard or expert config can be selected - on submit the "Unknown Error Occurred" message is given.

**Comment by jugla** [comment] 2021-05-29 13:00
Hello,
Since the last version V5.0.0 , I have added the use of matplotlib. Perhaps it is related to this.
Have you restarted HA. It has taken sometimes for me .
Please can you look in home-assistant.log if there is a keyword "Traceback" related to worldtidesinfocustom.
Thanks in advance
Philippe

**Comment by NigelReburn** [comment] 2021-05-29 13:11
Hi Phillippe,

Nothing in the logs relating to worldtides, yes I did a couple of restarts but the error remains. I ve not used this integration before and was about to take out an admiralty subscription but a HAC integration would be much better.

Thanks in advance for helping me :)

Regards,

Nigel Reburn

**Comment by jugla** [comment] 2021-05-29 13:27
Please, which type of HA version do you have ?
I use the core version on raspberry PI4. Just to be sure, can you look inside the following directory :  
`/srv/homeassistant/lib/python3.9/site-packages` if there are files/directory of `matplotlib` ?

**Comment by jugla** [comment] 2021-05-29 13:36
As a workaround, have you tried within configuration.yaml
with
```yaml
##configuration.yaml example
sensor:
  - platform: worldtidesinfocustom
    name: royan_tides
    api_key: YOUR_API_KEY
    latitude: 45.61949378902948
    longitude: -1.0318721687376207
```
Perhaps, it will failed but with a clear trace in `home-assistant.log`

**Comment by jugla** [comment] 2021-05-29 13:39
Here a try with bergen (norway):
![image](https://user-images.githubusercontent.com/59493499/120072381-f2226d00-c093-11eb-9b96-147645786630.png)

**Comment by NigelReburn** [comment] 2021-05-29 13:44
Hi, I have HA loaded on an UnRaid Unix server so I don’t see that Python directory.

Regards,

Nigel Reburn

**Comment by NigelReburn** [comment] 2021-05-29 13:45
I could try this if I csn find that yaml file (and my API key).

Regards,

Nigel Reburn

**Comment by NigelReburn** [comment] 2021-05-29 13:45
That looks absolutely perfect for what I want to do - I do hope I can get it to work1

Regards,

Nigel Reburn

**Comment by jugla** [comment] 2021-05-29 13:59
You succeed in !
- API key is from wordtidesinfo server : you can get a temporary key
- the configuration.yaml is below HomeAssistant home directory. In ~ /.homeassistant folder.

**Comment by NigelReburn** [comment] 2021-05-29 14:05
Ok thanks Phillippe, I will take a look later and let you know how it goes.

Regards,

Nigel Reburn

**Comment by NigelReburn** [comment] 2021-05-30 05:10
Hi Phillipe,

Thanks so much for your help - I am going to try to do this with a different site now as I didn’t realise it required a subscription - thanks/sorry.

Regards,

Nigel Reburn

**Comment by jugla** [comment] 2021-06-03 10:11
Hello
Any news Nigel ?
I will close this issue : if you have other questions , feel free

**Closed** 2021-06-03 10:11 UTC
Labels: bug, explanation, question

**Comment by NigelReburn** [comment] 2021-06-03 17:09
Hi Phillippe,

No I have no further questions thanks, please do close the issue and thanks very much for your help. I may come back to you to use this at a later date if the other system does not work.

Regards,

Nigel Reburn

**Comment by somar05** [comment] 2021-06-07 17:26
Hi. Just for information. I had same error (or similar): "Unknown Error Occurred" message and some errors related to the integration in logs (a few restarts tried). I try to configure as sensor (config.yaml), and after that the integration worked properly. After the integration works, I delete the sensor because HA said the "Platform worldtidesinfocustom does not generate unique IDs". After delete the sensors (config.yaml) all working ok. Thanks for the integration.

**Comment by jugla** [comment] 2021-06-07 20:21
Hello,
Thanks !
Please can you tell, what was your configuration i.e. worldtidesinfocustom never installed ?
Have you kept the trace (log) ?
Thanks in advance
Philippe

**Comment by somar05** [comment] 2021-06-08 04:48
Hi @jugla . Yes,  worldtidesinfocustom never installed before. Sorry, I'm not kept the error logs. Anyway, I'll try to delete integration to check if the error come back with no config.yaml 'trick'

**Comment by somar05** [comment] 2021-06-09 06:53
Hi again. I have tried to reproduce the issue, but it seems that after configure it as sensor (config.yaml) the first time, no errors are coming. That's include delete and reinstall integration

**Comment by jugla** [comment] 2021-06-10 06:13
Thanks !
I think it's because, matplotlib takes some time to be installed . This installation is triggered by HA when it analyses the worldtidesinfo's manifest.json file.
So when you remove the integration, you have left matplotlib.

It is my current guess.

**Comment by somar05** [comment] 2021-06-10 06:20
Therefore, all we have to do is wait a few minutes after the first restart. I have experienced similar situations with other HACS integrations. Thanks @jugla

**Comment by jugla** [comment] 2021-06-10 06:32
Thanks @somar05 !
